
services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    volumes:
      - ./elt:/opt/airflow/elt
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./gcp:/opt/airflow/gcp
    environment:
      - AIRFLOW_LOAD_EXAMPLES=False
      - AIRFLOW_CONN_GCP_DEFAULT: '{"key_path": "/opt/airflow/gcp/service_account.json", "project": "data-engineering-458813"}'
    ports:
      - "8080:8080"
    networks:
      - airflow_network
    command: >
      bash -c "airflow standalone"


networks:
  airflow_network:
    driver: bridge