
version: 2

models:
  - name: fact_books
    description: "A fact table containing book sales data"
    columns:
      - name: book_title
        description: "The title of the book"
        data_tests:
          - not_null
      - name: rating
        description: "The rating of the book"
        data_tests:
          - not_null

      - name: price
        description: "The price of the book"
        data_tests:
          - not_null
