sources:
  - name: online_books
    database: data-engineering-458813
    schema: online_books
    tables:
      - name: books
        columns:
          - name: book_title
            description: "Title of the book"
            tests:
              - not_null
          - name: price
            description: "Price of the book in USD"
            tests:
              - not_null
          - name: rating
            description: "Rating of the book"
            tests:
              - not_null
              - accepted_values:
                  values: ['One', 'Two', 'Three', 'Four', 'Five']
